<?php
/**
 * Created by PhpStorm.
 * User: joaob
 * Date: 13/08/2018
 * Time: 16:36
 */

namespace app\widget;

use yii\base\Widget;
use app\models\Alunos;
use app\models\Professores;
class Select extends Widget
{

    public $enableAlunoProfessor = true;

    public $alunos;
    public $professores;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        return true;
    }

    public function run()
    {
        parent::run();
        // TODO: Change the autogenerated stub
        $html = "<select class=\"form-control\">";
        if($this->enableAlunoProfessor){
            $this->professores = Professores::find()->all();
            foreach ($this->professores as $professor):
                $html .= "<option value='$professor->id'>".$professor->nome."</option>";
            endforeach;
        }else{
            $this->alunos = Alunos::find()->all();
            foreach ($this->alunos as $aluno):
                $html .= "<option value='$aluno->id'>".$aluno->nome."</option>";
            endforeach;
        }
        $html .= "</select>";


        return $html;
    }
}